[project]
name = "k-commerce"
version = "0.1.0"
requires-python = ">=3.11,<3.14"
dependencies = [
  "k-commerce-mcp",
]

[tool.uv.workspace]
members = [
  "packages/mcp",
]

[tool.uv.sources]
k-commerce-mcp = { workspace = true }

[dependency-groups]
dev = [
  "pytest>=8.4.1",
]

[tool.ruff]
line-length = 200

[tool.pytest.ini_options]
testpaths = ["tests"]
