from typing import NoReturn, Protocol

class Terminal(Protocol):
    def echo(self, message: str) -> None: ...

    def info(self, message: str) -> None: ...

    def warn(self, message: str) -> None: ...

    def abort(self, message: str) -> NoReturn: ...
