from typing import NoReturn, Protocol,Any
from collections.abc import Sequence

class Terminal(Protocol):
    def echo(self, message: str) -> None: ...

    def info(self, message: str) -> None: ...

    def warn(self, message: str) -> None: ...

    def abort(self, message: str) -> NoReturn: ...


class Prompts(Protocol):
    async def select(self, message: str, choices: Sequence[Any]) -> Any: ...

    async def text(self, message: str) -> str: ...

    async def print_message(self, message: str, *, style: str = "fg:red") -> None: ...
